### ISSUE TITLE
dex api default_account

### ISSUE THREAD

**Issue by mostar** [steemit/steem-python#1]
Hi,

In the dex documentation (http://steem.readthedocs.io/en/latest/convenience.html#dex)
You mention option for using default_account

It is not clear how you set default_account, so that I will not have to add it to the orders.
Please you please clarify this issue.

**Comment by Netherdrake** [comment]
Use `piston set` CLI command. I think its `piston set default_account <username>`

**Comment by mostar** [comment]
So in other to set it for my python script (API) first I need to run this CLI command?

**Comment by Netherdrake** [comment]
If you only have 1 steem account and want to omit `account=<username>` from your code, you can set `default_account` from CLI.

 It only needs to be set once, and all `steem-python` calls there on out will default to that account, unless `account=<username>` argument is present.
