### ISSUE TITLE
account.has_voted throws AttributeError

### ISSUE THREAD

**Issue by DoctorLai** [steemit/steem-python#103]
I am a fan of the steem-python library, and I think there is a bug in the *has_voted* method of the account class.

See this code:

```
from steem.account import Account
import sys

try:
  account = Account("justyy")
  if account.has_voted("@justyy/cn--2017-11-17"):
    print('voted already by has_voted')
except:
  print("Unexpected error:", sys.exc_info()[0])    
```

Let's run it using `python3 test.py` assuming above script is saved to `test.py`

It will **always** throws the `unexpected error - attribute error` which basically makes the method unusable.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510935862/pgfbptrtcnsw5ogpvetp.png)

The source code is at 136-138 of the official steem-python github page:
https://github.com/steemit/steem-python/blob/master/steem/account.py

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@justyy/account-hasvoted-throws-attributeerror">Utopian.io</a></em><hr/>

**Comment by crokkon** [comment]
Account.has_voted() expects a Post(), not a string:
```
from steem.account import Account
from steem.post import Post

try:
  account = Account("justyy")
  if account.has_voted(Post("@justyy/cn--2017-11-17")):
    print('voted already by has_voted')
except:
  print("Unexpected error:", sys.exc_info()[0])
