### ISSUE TITLE
Install steempy issue

### ISSUE THREAD

**Issue by abhi3700** [steemit/steem-python#106]
I have Windows 10 running on my laptop.
While installing the steem-python using pip, i found the following error in command prompt as follows:
Initially it asked for "Microsoft C++ 2015". then i installed that tool. And now it is showing error in opening "unistd.h" file.
Please, find the attached screenshots.....

![steempy_error screenshot 1](https://user-images.githubusercontent.com/16472948/33237032-6dbe5af8-d28d-11e7-9bd3-669dcb549df1.png)
![steempy_error screenshot 2](https://user-images.githubusercontent.com/16472948/33237037-7ef75bf8-d28d-11e7-94d0-729e8e6b2e10.png)
![steempy_error screenshot 3](https://user-images.githubusercontent.com/16472948/33237038-9864bac2-d28d-11e7-8cf3-80f1018827cb.png)
![steempy_error screenshot 4](https://user-images.githubusercontent.com/16472948/33237040-a1457096-d28d-11e7-8123-c1b041d69f3d.png)
![steempy_error screenshot 5](https://user-images.githubusercontent.com/16472948/33237043-a9a0e608-d28d-11e7-8013-249f406b0b79.png)

**Comment by Folken8** [comment]
I have the same issue

![error py](https://user-images.githubusercontent.com/31020925/34460508-c182f38a-ee10-11e7-97db-3acc2c50c477.png)

**Comment by holgern** [comment]
I wrote a tutorial for python anaconda:
https://steemit.com/utopian-io/@holger80/how-to-install-steem-python-for-windows

**Comment by cyon1c** [comment]
Currently, steem-python is compatible with Python 3.5 and up only. If you are able to use Python 3, you can run `pip3 install steem`.

If your environment requires 2.7, there is active development being done on branch `feature/python2_compat` to allow compatibility across both versions.

**Comment by holgern** [comment]
I release py-scrypt 0.8.3, which includes wheels for python 3.6. 
pip install scrypt is now possible on windows using python 3.6.
Read more here:
https://steemit.com/utopian-io/@holger80/py-scrypt-0-8-3-released

**Comment by holgern** [comment]
You can try my conda-forge version:
https://github.com/conda-forge/steem-feedstock
https://utopian.io/utopian-io/@holger80/install-steem-python-easily-by-conda-forge
