### ISSUE TITLE
steem_to_sbd and sbd_to_steem print misleading results

### ISSUE THREAD

**Issue by DoctorLai** [steemit/steem-python#109]
The Python github `convert.py` is located at:
https://github.com/steemit/steem-python/blob/master/steem/converter.py

Here is a test script to print the feed price:
```
from steem.converter import Converter          
import sys

try:                      
  converter = Converter()                
  steem_to_sbd = converter.steem_to_sbd(1.0)
  sbd_to_steem = converter.sbd_to_steem(1.0)
  print("1 STEEM = " + str(steem_to_sbd) + " SBD")
  print("1 SBD = " + str(sbd_to_steem) + " STEEM")          
except:
  print("Unexpected error:", sys.exc_info()[0])    
```

So it prints the following, which is quite misleading... at least, the SBD should be more expensive than STEEM, as of today.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513638315/wc06kl9joidruo7bcgcp.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@justyy/steemtosbd-and-sbdtosteem-print-misleading-results">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by E-D-A** [comment]
That is by design as 1 SBD is worth 1 USD. It is the market that is misleading, wanting to pay 10 times more.  :) Also, the average price is used, hence it is showing only 2.2SBD for 1 STEEM.
The whole system could be questioned, but this is just how it works at the moment.
