### ISSUE TITLE
Python2 Support

### ISSUE THREAD

**Issue by cyon1c** [steemit/steem-python#128]
This is a broader issue to document and track the progress of adding Python2 support to steem-python

#Subissues

- [x] Remove Breaking Python 3 Syntax #138 
- [x] Backport Testing #135 
- [x] Unify Bytes handling #157

**Comment by sneak** [comment]
the first one i found was steembase/base58.py

**Comment by cyon1c** [comment]
I'm going to work through each of these and catalogue any relevant documentation for reference sake.

[Dict-merging in Python2](https://stackoverflow.com/questions/38987/how-to-merge-two-dictionaries-in-a-single-expression) - steem/account.py line 220.

**Comment by cyon1c** [comment]
Issue is blocked by Issue #135 . Don't want to PR this until the package is passing all tests.
