### ISSUE TITLE
these codes may be incorrect

### ISSUE THREAD

**Issue by hakancelik96** [steemit/steem-python#142]
I don't get it right here is there a code redundancy, or it is written incorrectly,
maybe 
```python
if not account:
    account = configStorage.get("default_account")
    raise ValueError("You need to provide a voter account")
```
but these codes are wrong because of the raise, if run raise code ,vote  function is stop

https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L370

https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L373

same wrong
https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L491

same 
https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L639

same
https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L686

--
https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L714

--
https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L747

-
https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L782

-
https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L825

--
https://github.com/steemit/steem-python/blob/f3db5e3d9bb6d98a8e2286c91b050813f3311dcc/steem/commit.py#L862

continues ...

**Comment by E-D-A** [comment]
The first 'if-statement' will check if you manually provided an account. If not, then it will try to fetch the default configured account in your wallet. If that still returns nothing, then it will raise the exception.
I hope that explains it and I hope that is what you were asking. :smile:

**Comment by hakancelik96** [comment]
yes I understand but it could be better this way
```python
 if not account:
    account = configStorage.get ("default_account")
    if not account:
        raise ValueError ("You need to provide a voter account")
```
never mind,I close this issue, thank you
