### ISSUE TITLE
[Errno -2] Name or service not known

### ISSUE THREAD

**Issue by RJCM** [steemit/steem-python#143]
Hello everyone..!

I'm newbie and  have a problem when I run the s.get_account ('UserName') instruction python enters a loop showing the following message ....

**WARNING:urllib3.connectionpool:Retrying (Retry(total=19, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb665594c>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /**

...then I break it with Ctrl+"C"

I'm using:
- Ubuntu Bionic Beaver (development branch)
- Python 3.6.3

**Comment by hakancelik96** [comment]
use this codes 
```python
from steem import Steem
steem = Steem(nodes=['https://api.steemit.com'])
```

**Comment by RJCM** [comment]
The above code did not work.

Try the issue code # 14  [https://github.com/steemit/steem-python/issues/14]
       **`steempy set nodes https://api.steemit.com`**

and it worked..!!!

**Comment by damasta2k** [comment]
i still get the same error...was this issue resolve? I have syntax error when use steempy set nodes https://api.steemit.com

**Comment by hakancelik96** [comment]
read this https://steemit.com/steemit/@crokkon/steem-blockchain-access-with-python-setting-up-steem-python-with-docker

**Comment by jtbitz** [comment]
I have the appropriate output when I run $ `steempy info`, i have tried `steempy set nodes https://api.steemit.com`, and I still get 

![image](https://user-images.githubusercontent.com/38632577/39098465-61efb602-4639-11e8-8ec8-e88679d72705.png)

Thoughts?
