### ISSUE TITLE
change 

### ISSUE THREAD

**Issue by dzyk** [steemit/steem-python#145]
can i take all posts?
s = steem
b = s.blog.Blog('mgu', steemd_instance=client)
po = b.all()
print (po)
for i in po:
    print (i)

print only
<generator object Blog.all at 0x7fa537e60a98>
...

**Comment by Netherdrake** [comment]
Blog is lazy by default, and returns a generator. To read all posts, you could do this:
```
for post in s.blog.Blog('mgu'):
    print(post)
```
