### ISSUE TITLE
What is an archived post?

### ISSUE THREAD

**Issue by kirkins** [steemit/steem-python#150]
I'm trying to have a bot vote on posts of certain users.

I keep getting an exception about not being able to vote on archived posts.

I'm searching google and I can't find anything about what is an archived post on Steem.

Can someone explain the code block below:

```
        # Test if post is archived, if so, voting is worthless but just
        # pollutes the blockchain and account history
        if self.get('net_rshares', None) == None:
            raise VotingInvalidOnArchivedPost
        return self.commit.vote(self.identifier, weight, account=voter)
```

https://github.com/steemit/steem-python/blob/master/steem/post.py#L247-L251

**Comment by cyon1c** [comment]
Currently, an "archived" post is one which is older than 7 days, and can no longer be voted on. Are these posts you are trying to vote on within the 7 day range, or older?

**Comment by kirkins** [comment]
No apparently the code I posted is the fixed version but it isn't on pip.

**Comment by kirkins** [comment]
Closing as issue is open for that here https://github.com/steemit/steem-python/issues/27
