### ISSUE TITLE
blockchain.stream_from nodes?

### ISSUE THREAD

**Issue by firemouse604** [steemit/steem-python#156]
im not having any luck with blockchain.stream  on any node...

Is there a list of nodes that support this functionality?

**Comment by E-D-A** [comment]
Please specify what failed. A snippet of your code and the output showing the error would be helpful.
For sure it works. :smile: Tested recently against rpc.buildteam.io, api.steemit.com & rpc.steemviz.com.

**Comment by firemouse604** [comment]
it just sits there forever and doesn't do anything... like it's not finding any posts


custom_instance = Steemd(nodes='rpc.buildteam.io')
b = Blockchain(steemd_instance=custom_instance)

stream = b.stream()
for post in stream:
     if 'title' in post:
          title = post['title']
          print('title')

**Comment by crokkon** [comment]
I think nodes should be a list, not a string. This works for me:

```python
>>> from steem.blockchain import Blockchain
>>> from steem.steem import Steem
>>> s = Steem(nodes=['https://rpc.buildteam.io'])
>>> b = Blockchain(s)
>>> for post in b.stream():
...     print(post)
```

**Comment by clayop** [comment]
I failed with nodes list `['127.0.0.1:8090']`

**Comment by firemouse604** [comment]
this is still an issue.

**Comment by cyon1c** [comment]
Will look into this issue this week.

**Comment by idikuci** [comment]
Hey, Is this still an outstanding error? I get it too.
