### ISSUE TITLE
Installing steem

### ISSUE THREAD

**Issue by tomole444** [steemit/steem-python#160]
After trying to install steem with
 `sudo pip3.6 install steem`
I get this result:
Collecting steem
  Using cached steem-0.18.103.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dcixdwct/steem/setup.py", line 8, in <module>
        import package_meta # this is a simple tool for loading metadata from Pipfile and other places
      File "/tmp/pip-build-dcixdwct/steem/package_meta.py", line 10, in <module>
        from setuptools.config import read_configuration
    ModuleNotFoundError: No module named 'setuptools.config'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dcixdwct/steem/

**Comment by cyon1c** [comment]
I just installed `steem` on a fresh ubuntu install and this issue is caused by not having `setuptools` installed. `pip3 install setuptools` should fix this.

**Comment by tomole444** [comment]
I tried but the answer was:
`sudo pip3 install setuptools
Requirement already satisfied: setuptools in /root/.local/lib/python3.5/site-packages
`

**Comment by cyon1c** [comment]
@tomole444 easiest thing to do right now is pull from `master` here on github and install locally. We've had significant updates to the library in the past two weeks that haven't made it up to PyPi yet. Refer to the Readme on the steps to clone and install the library.

**Comment by tomole444** [comment]
When I try "sudo python install setup.py" I get this error:
`python install setup.py
python: can't open file 'install': [Errno 2] No such file or directory
`

**Comment by tomole444** [comment]
OK I think I solved it
