### ISSUE TITLE
Crypto.Util.py3compat cannot import name 'byte_string'

### ISSUE THREAD

**Issue by puzzledbytheweb** [steemit/steem-python#175]
I have this simple code:

```
from steem import Steem

s = Steem();

balance = s.get_account('puzzledbytheweb')['sbd_balance']


print(balance)
```
Error appears here 
```
File "C:\Program Files\Microsoft Visual Studio\Shared\Python36_86\lib\site-packages\Crypto\Util\_raw_api.py", line 32, in <module>
    from Crypto.Util.py3compat import byte_string
ImportError: cannot import name 'byte_string'
```

Any idea on how to solve this issue?

Thanks!!

**Comment by bobinson** [comment]
I think you managed to fix by re-installing ?

**Comment by puzzledbytheweb** [comment]
Hey! Ok, I will try. The installation so far as been a pain (in windows 7) with problems with pycrypto and python version (I'm using 3.6). This afternoon I will reinstall and hopefully everything will go as planned!

**Comment by cyon1c** [comment]
@puzzledbytheweb apologies for the problems installing the library.

I would highly recommend trying to install with [`pipenv`](https://docs.pipenv.org/) . I can't speak to it's ease of setup on Windows, but it should give you a deterministic environment to install and run Python code.
