### ISSUE TITLE
steempy importaccount - global name 'future_bytes' is not defined

### ISSUE THREAD

**Issue by rossbulat** [steemit/steem-python#176]
I am having issues importing my account, on both Ubuntu and macOS 10.13.3 using virtualenv.

Python version: 2.7

After the key phrase and wallet password prompt, I am met with this traceback:

Traceback (most recent call last):
  File "/steemit/bin/steempy", line 11, in <module>
    load_entry_point('steem==0.18.3', 'console_scripts', 'steempy')()
  File "build/bdist.linux-x86_64/egg/steem/cli.py", line 1153, in legacyentry
  File "build/bdist.linux-x86_64/egg/steem/wallet.py", line 217, in addPrivateKey
  File "build/bdist.linux-x86_64/egg/steem/wallet.py", line 150, in newWallet
  File "build/bdist.linux-x86_64/egg/steembase/storage.py", line 367, in __init__
  File "build/bdist.linux-x86_64/egg/steembase/storage.py", line 388, in saveEncrytpedMaster
  File "build/bdist.linux-x86_64/egg/steembase/storage.py", line 412, in getEncryptedMaster
  File "build/bdist.linux-x86_64/egg/steembase/storage.py", line 402, in deriveChecksum
NameError: global name 'future_bytes' is not defined

Is there a way to overcome this?

**Comment by bobinson** [comment]
Is it possible for you to setup Python 3.6 ?

**Comment by rossbulat** [comment]
@bobinson I am met with all sorts of errors installing modules using python3.6

**Comment by bobinson** [comment]
@rossbulat  - here is steps to install it on linux. With brew install it should be possible to install on Mac as well. 

https://steemit.com/howto/@fortunex/installing-python-3-6-on-ubuntu-16-04

**Comment by rossbulat** [comment]
Thank you @bobinson, I will give this guide a shot.

**Comment by rossbulat** [comment]
Thank you @bobinson. My issues were with installing the modules, not with installing python itself. I will go ahead and see if following these steps fix the errors I was facing.

**Comment by bobinson** [comment]
@rossbulat  - its a known issue. The link I shared has the fix i the comments.

**how to fix ?**

edit /usr/local/lib/python3.6/dist-packages/steem-0.18.103.dist-info/METADATA and change

*toml (==0.9.3.1)*

to

*toml (==0.9.3)*

**Comment by causenet** [comment]
I met the same error: NameError: global name 'future_bytes' is not defined

just change future_bytes to bytes and run setup.py again, will fix the problem.

**Comment by cyon1c** [comment]
@causenet Unfortunately no, that will not fix your issue. It will allow you to potentially run `steem-python`, but much of the underlying codebase utilizes the `future_bytes` utility to ensure `bytes` objects function the same in 2.7 as they do in 3.6.

That said, this appears to be a bug I missed due to relying to heavily on unit tests to ensure doneness. I will bring this into the next sprint and get it resolved.
