### ISSUE TITLE
RPC Error on operations using Steem Python

### ISSUE THREAD

**Issue by Boontjie** [steemit/steem-python#187]
I am getting 'Bad Cast : Invalid cast from string_type to Array' when performing a Transfer operation

**Comment by cryptohustlin** [comment]
same issue.

I think it has to do with removing the @ from the code?

**Comment by Boontjie** [comment]
It is unlikely to be the @, I was running old code before the removal.  Steemit has changed the API on their side.  Some stuff broke today

**Comment by camponez** [comment]
Could be somewhat related to #188

**Comment by E-D-A** [comment]
As far as I can see this is only relevant for api.steemit.com. Other nodes are responding as expected.

**Comment by Boontjie** [comment]
Thanks, it means steemit inc screwed up their node
