### ISSUE TITLE
Claiming Reward Balance gives MissingKeyError

### ISSUE THREAD

**Issue by camponez** [steemit/steem-python#188]
I was trying to use the claim_reward_balance(). It worked for sometime, but two days ago it stops working.

The code:

```python
from steem import Steem
from steem.commit import Commit

c =  Commit(steem=Steem(keys=[POST_KEY, ACTIVE_KEY]))

 c.claim_reward_balance()
```
```
MissingKeyError                           Traceback (most recent call last)
<ipython-input-6-537da9054b42> in <module>()
----> 1 c.claim_reward_balance()

/usr/local/lib/python3.6/dist-packages/steem-1.0.0-py3.6.egg/steem/commit.py in claim_reward_balance(self, reward_steem, reward_sbd, reward_vests, account)
    912                 "reward_vests": reward_vests,
    913             })
--> 914         return self.finalizeOp(op, account, "posting")
    915
    916     def delegate_vesting_shares(self, to_account, vesting_shares,

/usr/local/lib/python3.6/dist-packages/steem-1.0.0-py3.6.egg/steem/commit.py in finalizeOp(self, ops, account, permission)
    130         else:
    131             tx.appendSigner(account, permission)
--> 132             tx.sign()
    133
    134         return tx.broadcast()

/usr/local/lib/python3.6/dist-packages/steem-1.0.0-py3.6.egg/steem/transactionbuilder.py in sign(self)
    119
    120         if not any(self.wifs):
--> 121             raise MissingKeyError
    122
    123         signedtx.sign(self.wifs, chain=self.steemd.chain_params)

MissingKeyError:
 ```

**Comment by Boontjie** [comment]
I am not getting a missing key error, but also Bad Cast on claiming reward balance, see #187 .  I think new changes affect all 'call' operations where parameters are passed.  I am not sure how to restructure them to work at this point in time

**Comment by Boontjie** [comment]
See my issue, try not using api.steemit node

**Comment by camponez** [comment]
I can't even get the error anymore. ``stempy config`` just hangs there as does ``c =  Commit(steem=Steem(keys=[POST_KEY, ACTIVE_KEY]))``. 

Where do I clear the ``steempy`` configuration?

**Comment by cyon1c** [comment]
This is due to our switch to appbase on `api.steemit.com`, and those changes not being included in `steem-python`. I will be working to get this resolved today.

**Comment by bobinson** [comment]
@cyon1c  - thats some exciting news!

**Comment by camponez** [comment]
I get this error on different using other api...

**Comment by roadscape** [comment]
@camponez try using this code as reference:
https://github.com/steemit/steem-python/pull/195/files#diff-94ce5c94e607bee610742036bb262f0eR23

**Comment by firemouse604** [comment]
I can't get s.claim_reward_balance(account=wif)  to work with any node.  This functionality stopped working for me a few weeks ago

**Comment by cyon1c** [comment]
Do you have a list of nodes you've tried against? @firemouse604

**Comment by camponez** [comment]
Weird... I'm still seeing this problem but just with one of my accounts...

**Comment by camponez** [comment]
> Weird... I'm still seeing this problem but just with one of my accounts...

On the account that it's working I get the error: `ERROR:root:Downgrade-retry steemd.minnowsupportproject.org`

**Comment by roadscape** [comment]
Is anyone able to confirm this issue is resolved on `master` branch?

**Comment by firemouse604** [comment]
Yes, just updated and it seems to be resolved now. Thank you.

**Comment by roadscape** [comment]
@camponez if it only affects 1 account it's probably due to a WIF/config issue.

I believe the other concerns in this issue should be resolved now, please leave a comment if this is not the case.

**Comment by camponez** [comment]
@roadscape Yes. Same problem. It only works for one account, not work for two others....

>if it only affects 1 account it's probably due to a WIF/config issue.

I'm able to call `check_reward()`. Only `claim()`, does not work. I can also vote with those accounts. Only `claim()` has the problem. Very weird to be for 1 of 3 accounts only.

**Comment by roadscape** [comment]
@camponez you might be using an old version. We need to update the pypi repo still. I recommend checking your script against `master` on this repository.

**Comment by camponez** [comment]
@roadscape I thought that I was running master. I'm doing `sudo python setup.py install` in the master branch. 
```
$ steempy --version
steempy 1.0.0
```

is there another way to check which version I'm running?

**Comment by cyon1c** [comment]
Hey @camponez, I want to trouble shoot a couple things  did you use git to clone the repo? If so, can you run `git pull origin master` and then `git log` to check that you have all the newest changes by comparing the last commit hash with the tip of master on github. 

I noticed your command is `sudo python setup.py install`, which means you've installed `steem-python` as a Python 2 library. In your original logs, your traceback shows you are using Python 3.6. I would recommend trying `python3 setup.py install` and then try this again.

If this still does not work, re-importing the account should solve the issue. In the event that still does not, please report back and I can re-open and investigate further.

**Comment by camponez** [comment]
@cyon1c 
- I'm pretty sure I'm on master (a2a5e58ad67f75829add)
- My python is 3.6 
```
$ python --version
Python 3.6.3
```
Also
```
 ls /usr/local/lib/python3.6/dist-packages/steem-1.0.0-py3.6.egg
```

However, when I run on `ipython`:
```
import steem
help(steem)
NAME
    steem - # -*- coding: utf-8 -*-

PACKAGE CONTENTS
    account
    aes
    amount
    block
    blockchain
    blog
    cli
    commit
    converter
    dex
    instance
    post
    profile
    steem
    steemd
    transactionbuilder
    utils
    wallet
    witness

VERSION
    0.18.103

FILE
    /usr/local/lib/python3.6/dist-packages/steem-1.0.0-py3.6.egg/steem/__init__.py
```

**Comment by camponez** [comment]
I found the error!

It's strange because it had worked before. Problem was on my code. I needed to pass `account`to `c.claim_reward_balance()`

Look good now! :)
