### ISSUE TITLE
Unexpected behavior in Steem() function with custom nodes

### ISSUE THREAD

**Issue by CStiller** [steemit/steem-python#189]
Error description:
When calling Steem(nodes=["https://api.example","https://api.steemit.com"]) and the first node ("https://api.example") is not reachable or delivers invalid data the application crashes with an unhandled exception.

Expected behavior: Steem() uses the second node as fallback with logging info.

example error log(42,9 kB):
[error.txt](https://github.com/steemit/steem-python/files/1845909/error.txt)

**Comment by cyon1c** [comment]
@CStiller This should be resolved on master, let us know if you are still having any issues.
