### ISSUE TITLE
account.py generator functions (get_account_history, history, history_reverse) cannot retrieve blockchain transactions older than 30 days

### ISSUE THREAD

**Issue by outlier89** [steemit/steem-python#197]
While retrieving transactions of a particular account, any generator function only fetches last 30 days transactions along with the transaction of the account creation (index 0 transactions). There is no way to access any transaction older than 30 days. Please rectify this issue as soon as possible.

**Comment by cyon1c** [comment]
This is due to the switch to AppBase on `api.steemit.com`. We will be working to restore account history functionality on that node soon. If this functionality is critical, I would recommend switching to another node for the time being.

**Comment by outlier89** [comment]
Thanks a lot for the quick reply.
