### ISSUE TITLE
Streaming blocks throws an exception when global props fail to return

### ISSUE THREAD

**Issue by aaroncox** [steemit/steem-python#20]
```
Traceback (most recent call last):
  File "bot.py", line 57, in <module>
    for block in b.stream_from(batch_operations=True):
  File "/usr/local/lib/python3.5/dist-packages/steem/blockchain.py", line 72, in stream_from
    head_block = self.get_current_block_num()
  File "/usr/local/lib/python3.5/dist-packages/steem/blockchain.py", line 40, in get_current_block_num
    return self.info().get(self.mode)
AttributeError: 'NoneType' object has no attribute 'get'
```

I've been experimenting with a voting bot and at least once a day this is crashing the script. 

I'd be willing to fix this myself - but I'm not sure what the preferred approach would be. Should the `info` call be prevented from returning a `NoneType` object, or should there be a retry of fetching the info, or finally should there just be an `if` statement to ensure it's a dict before it calls `get` on it.

**Comment by Netherdrake** [comment]
I think in this case we could.
1.) Cache the head number.
2.) If info() is None, return cached value.
