### ISSUE TITLE
http_client.py - steembase.exceptions.RPCError: Internal Error

### ISSUE THREAD

**Issue by puzzledbytheweb** [steemit/steem-python#209]
Hello!

I am having this error:
`File "/usr/lib/python3.6/site-packages/steembase/http_client.py", line 263, in _return
    raise RPCError(error_message)
steembase.exceptions.RPCError: Internal Error`

It happens when creating an alias such as `s = Steem()`. I am a noob in programming and I am trying to do a project to help me learn faster and in a more meaningful way, I believe this problem has something to do with "http_client.py" but I am not sure if it is a "script" problem or something to do with the connection to the blockchain (if it happens when creating an alias).

This is temporary and seems that by rebooting the system it works, I am posting this just to report and to ask if I should be wary of malfunction when I deploy my little app, and if is "safe" to reboot the server in which my app should be hosted (maybe a dumb question :p).

I am working on Manjaro Linux (based on Arch Linux) with Kernel version 4.14.31.

Cheers!

**Comment by cyon1c** [comment]
@puzzledbytheweb Thank you for reaching out and filing an issue. Currently `steem-python` is undergoing a significant face lift alongside the release of HF 19.4 & AppBase. these issues are actively being worked on, that said, we will be releasing some big updates to PyPi soon, until then you can pull from master and install locally if you want to use these updates before they get to PyPi.
