### ISSUE TITLE
Voting Power does not update until a new vote is cast.

### ISSUE THREAD

**Issue by bigdeej** [steemit/steem-python#23]
The value in "voting_power" returned from steemd.get_account("myaccount") does not update until after I make a new vote on steemit.com. The value will update to the correct "Voting Power" after I cast a new vote, however it does not update again until I cast another vote. It appears to not take into account the replenishing of the Voting Power until a new vote is cast under your account. Steemd.com appears to have the correct value. Any ideas what is going on, it seems steemdb.com has the same lag. Thanks!

**Comment by steemypete** [comment]
This is how steem works and you have to calculate it yourself using the time since the last vote.
