### ISSUE TITLE
Bad or missing upstream response

### ISSUE THREAD

**Issue by BhuzOr** [steemit/steem-python#246]
### Version of Python you are running ###

3.6.3

### Version of steem-python you are running ###

1.0.0 (I think xD)

### Expected Behavior ###

get block info

### Actual Behavior ###

`unspecified error from api.steemit.com (Bad or missing upstream response) in get_block`

### Steps to reproduce ###

randomly on `get_block` calls

**Comment by roadscape** [comment]
PR: https://github.com/steemit/steem-python/pull/248

**Comment by roadscape** [comment]
#248 was merged.
