### ISSUE TITLE
Voting not possible on posts, which has no votes 

### ISSUE THREAD

**Issue by amainz** [steemit/steem-python#27]
I get an exception of:
<class 'steembase.exceptions.VotingInvalidOnArchivedPost'>

While voting on a post, which has right now no votes at all. 

According to the code "net_rshares = 0" is an indication for a test post. But also for a fresh one.
 
`       

        def vote(self, weight, voter=None):
        """ Vote the post

            :param float weight: Weight for posting (-100.0 - +100.0)
            :param str voter: Voting account
        """
        # Test if post is archived, if so, voting is worthless but just
        # pollutes the blockchain and account history
        if not self.get('net_rshares'):
            raise VotingInvalidOnArchivedPost
        return self.commit.vote(self.identifier, weight, account=voter)`

**Comment by Netherdrake** [comment]
Fixed https://github.com/Netherdrake/steem-python/commit/87510e1a194bac1f636b138df02e47f4b1d6cfd2

**Comment by aditya-ramabadran** [comment]
This is still not fixed in steemit/steem-python, and I consider this to be quite a major issue.

I'm resorting to using `.commit.vote` rather than `.vote` due to this issue.

**Comment by kirkins** [comment]
Hi I'm getting this error.

`VotingInvalidOnArchivedPost()`

**Comment by kirkins** [comment]
Strange looking at your fix @Netherdrake it seems the current code base is the exact same to the fixed commit posted (aside from `and` vs `==`).

I will have to switch to your fork.

**Comment by cutetechie** [comment]
Did @Netherdrake fix solved it?
I am also getting the `VotingInvalidOnArchivedPost()` exception.

**Comment by kirkins** [comment]
Was this fixed, I tried to update package via pip but still seeing the error.

**Comment by kirkins** [comment]
Ok, just installed based on the README instead and it is working
