### ISSUE TITLE
How to set the"reward options" ? (100%SP, 50/50 and None)

### ISSUE THREAD

**Issue by Degram** [steemit/steem-python#275]
How to set the"reward options" when i submit a post ?
I'm talking about the choices you have when you post 
100% Steem Power
50% SBD and 50% SP
Decline Payout

**Comment by fraenk** [comment]
it's all in the "options"

`post(title, body, author, permlink=None, reply_identifier=None, json_metadata=None, comment_options=None, community=None, tags=None, beneficiaries=None, self_vote=False)`

comment_options (str, dict) –
JSON options object that can be attached to the post. Example:

```
comment_options = {
    'max_accepted_payout': '1000000.000 SBD',
    'percent_steem_dollars': 10000,
    'allow_votes': True,
    'allow_curation_rewards': True,
    'extensions': [[0, {
        'beneficiaries': [
            {'account': 'account1', 'weight': 5000},
            {'account': 'account2', 'weight': 5000},
        ]}
    ]]
}
```

**Comment by Degram** [comment]
Ok i have to set 'percent_steem_dollars' to 0 and all reward will be Steem power (100%) ?
