### ISSUE TITLE
steem-python RPCError: (Assert Exception:var.is_object(): Asset has to treated as object.) in verify_authority

### ISSUE THREAD

**Issue by Zaehyeon2** [steemit/steem-python#290]
### Version of Python you are running ###
python3.6.8

### Version of steem-python you are running ###
1.0.1

### Expected Behavior ###
send http to dev blockchain network

### Actual Behavior ###
rasing RPCError

### Stack Trace ###
failing on assert_exception from 166.104.245.104 (Assert Exception:var.is_object(): Asset has to treated as object.) in verify_authority

**Comment by Zaehyeon2** [comment]
{'ref_block_num': 26220, 'ref_block_prefix': 3936935949, 'expiration': '2019-08-30T13:00:42', 'operations': [['report_vote', {'voter': 'test1', 'user': 'test1', 'report_id': '2019082114464417926', 'bet_balance': '1.000 STEEM', 'tf': True}]], 'extensions': [], 'signatures': ['20504338b5e8f6f3ed9da8a52e3ca8396a28e21eb8df63958334825f4a073ca8114af1ea1255cbabc2cbc4125d127a100f1d612de578ad0510e507a0775a4c13cb']}

**Comment by roadscape** [comment]
`report_vote` is not a valid steem operation, it looks like you want to broadcast a `custom_json` op instead.
