### ISSUE TITLE
steem.post() doesn't work when contains single quotes in body

### ISSUE THREAD

**Issue by oflyhigh** [steemit/steem-python#4]
I encountered some problems when I tried to use python-steem to post on steemit.
I will simplify the problem into the following code

```
from steem import Steem

tags=['test', 'spam']

content1 = "Test only, don't upvote"
content2 = "Test only, dont upvote"

steem=Steem()
steem.post(title='test only', body=content1, author='oflyhigh', tags=tags)
print("Done!")
````

The content1 doesn't work but content2 works well.
And all of them work well under piston.

So, what's wrong?

---------------
Error message:
>ValueError: Invalid TransactionBuilder Format

**Comment by Netherdrake** [comment]
Thank you for reporting this :)

**Comment by oflyhigh** [comment]
You are welcome!
