### ISSUE TITLE
Update requirements; funcy v1.9 not compatible

### ISSUE THREAD

**Issue by bennierex** [steemit/steem-python#50]
In the funcy module (currently at v1.9), they moved functions from `funcy.simple_funcs` to `funcy.funcs`:
```
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    from steem.blockchain import Blockchain
  File "/Users/ben/.pyenv/versions/steemit-test/lib/python3.6/site-packages/steem/__init__.py", line 2, in <module>
    from .steem import Steem
  File "/Users/ben/.pyenv/versions/steemit-test/lib/python3.6/site-packages/steem/steem.py", line 1, in <module>
    from .commit import Commit
  File "/Users/ben/.pyenv/versions/steemit-test/lib/python3.6/site-packages/steem/commit.py", line 20, in <module>
    from .account import Account
  File "/Users/ben/.pyenv/versions/steemit-test/lib/python3.6/site-packages/steem/account.py", line 8, in <module>
    from funcy.simple_funcs import rpartial
ModuleNotFoundError: No module named 'funcy.simple_funcs'
```

Please update `account.py` to use the new import path or fix version dependency to `funcy==1.8`.

**Comment by MarneeDear** [comment]
We could make this backward compatible by wrapping the import statement in a try catch block. So if python cant find one path it uses another. This makes it possible to use funcy 1.9 or lower, depending on what is installed.

**Comment by bennierex** [comment]
@MarneeDear yes that could work. However, I'm not sure about possible side effects because of other incompatible changes in funcy 1.9. I'll try to find out more about that.

**Comment by Suor** [comment]
One should not import from `funcy.whatever` but from `funcy` directly. Any internal modules (with the exception of py2 and py3 adapters) are not public interface and could change.

**Comment by Netherdrake** [comment]
@Suor Thank you for `funcy`. Its one of my favorite Python libraries.

**Comment by Suor** [comment]
@Netherdrake you are welcome )

Few things on funcy usage here:

- `list(pluck(...))` could be replaced with `lpluck()`. Most funcy sequence funcs have list versions.
- `filter(bool, map(f, seq))` could be written as `keep(f, seq)`.
- to flatten one level it safer to use `cat()/lcat()`:

```python
list(flatten([list(x.get_replies()) for x in comments]))
# same
lcat(x.get_replies() for x in comments)
```

**Comment by aditya-ramabadran** [comment]
It seems the original `account.py` issue was already fixed. The new statement is:
`from funcy import rpartial`
which should be backwards-compatible as well.

**Comment by Suor** [comment]
I probably should state explicitly that funcy has no backwards incompatible changes since 1.0 for anyone reading this in the future.

**Comment by cyon1c** [comment]
@Suor thanks for dropping by with the update.
