### ISSUE TITLE
Random Error?

### ISSUE THREAD

**Issue by RicRock** [steemit/steem-python#52]
I seem to randomly get the error below.

Example:
now < trx.expiration:
    {"now":"2017-09-18T00:44:00","trx.exp":"2017-09-18T00:43:34"}
    th_a  database.cpp:2857 _apply_transaction

I've had it happen during submitting a post, attempting an upvote, and transferring funds.

It appears that my VPS is at least 26 seconds off but it is not.

Is there something that I can adjust and extend the transaction expiration?

TIA
Ric

**Comment by cenpengzhu** [comment]
Same error.You can adjust the expiration by "steem.commit.expiration".The default value is 60. It worked for me.

**Comment by cyon1c** [comment]
Please leave a comment here if you are still having issues. Closing.
