### ISSUE TITLE
import account error

### ISSUE THREAD

**Issue by bycz6** [steemit/steem-python#6]
I'm trying to run the cli wallet but always getting this error!

![image](https://cloud.githubusercontent.com/assets/23620619/26609638/273d38fe-459a-11e7-9eaa-e40ecf5021fb.png)

**Comment by Netherdrake** [comment]
The second passphrase is your BIP38 wallet one, not your steem account.

Also, does your BIP38 wallet password contain any special characters?

**Comment by bycz6** [comment]
Ok, so how i create a BIP38 wallet?

**Comment by Netherdrake** [comment]
The wallet is created automatically, the first time you import a Steem account, or a private key.

**Comment by bycz6** [comment]
thanks a lot! It work.
Just one more question how I make my script to run without asking the password everytime?

**Comment by Netherdrake** [comment]
You can set `UNLOCK` environment variable, with your password.

**Comment by bycz6** [comment]
Thanks
