### ISSUE TITLE
win7 python 3.6  ( Building wheels for collected packages: ujson )

### ISSUE THREAD

**Issue by keepcalmandread** [steemit/steem-python#90]
win 7
python 3.6
i try install with:

pip install -U steem

> Building wheels for collected packages: ujson
  Running setup.py bdist_wheel for ujson ... error
  Failed building wheel for ujson
  Running setup.py clean for ujson
Failed to build ujson
Installing collected packages: ujson
  Running setup.py install for ujson ... error
Exception:
Traceback (most recent call last):
  File "C:\Users\hayrettin\Anaconda3\lib\site-packages\pip\compat\__init__.py",
line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 48: invalid
 start byte

![cmd ujson](https://user-images.githubusercontent.com/32783415/32081930-ea3326fc-bac0-11e7-84f9-da584cb7c133.jpg)

**Comment by holgern** [comment]
https://steemit.com/utopian-io/@holger80/how-to-install-steem-python-for-windows

conda install ujson
