### ISSUE TITLE
Need more description about dependency 

### ISSUE THREAD

**Issue by clayop** [steemit/steem-python#91]
The newer version seems require python 3.6 (while 16.04 LTS has 3.5.2 as a default). It would be better to describe details of dependency and supports for old version users.

**Comment by pgarciagon** [comment]
I agree. Support of the latest LTS ubuntu version should be garanteed. Moreover, the mayority of steem nodes are running 16.04, and a lot of scripting is done with steem-python. A upgrade of steem-python could break important maintenance scripts (fail-overs etc).

**Comment by cyon1c** [comment]
These issues should be resolved with commit [1d7e7f3](https://github.com/steemit/steem-python/commit/1d7e7f3a62ec180a986f0d4504939e822bc194be).
