### ISSUE TITLE
delegate_vesting_shares does not honor UNLOCK env var

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/steem-python#98]
I keep getting this message with the official version of steem-python (0.18.103) when using export UNLOCK=<wallet password>

steembase.exceptions.MissingKeyError 

If I do steem = Steem(keys=[]) it works fine.

When using Netherdrake's version, it works fine off the environment variable.

Is this expected, or is it a bug?

**Comment by E-D-A** [comment]
I also had this issue a few months back so I also implemented a workaround.
When I tested it again a few weeks ago, it worked as expected. So everything thing seems fine now.

**Comment by themarkymark-steem** [comment]
I had a similar issue with post.reply but it didn't work with wallet.unlock() but worked with Env var.

**Comment by cyon1c** [comment]
@themarkymark-steem Closing for the time being. If this is still an issue please let add as detailed as a description as you can covering the error and we'll investigate further.
